"""
Production FastAPI Microservice for Gradient Boosting Classifier.
Auto-generated by Atlas CLI Deployment Generator.
"""
from __future__ import annotations

import logging
import asyncio
import json
import shutil
import subprocess
import sys
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

if sys.platform == "win32":
    try:
        asyncio.set_event_loop_policy(asyncio.WindowsProactorEventLoopPolicy())
    except Exception:
        pass

import joblib
import numpy as np
import pandas as pd
from fastapi import FastAPI, File, Form, HTTPException, UploadFile
from fastapi.responses import FileResponse
from fastapi.middleware.cors import CORSMiddleware

from schemas import (
    PredictionBatchInput,
    PredictionBatchOutput,
    PredictionInput,
    PredictionOutput,
    ServiceInfo,
)

logger = logging.getLogger("model_service")
logging.basicConfig(level=logging.INFO)

PROJECT_DIR = Path(__file__).resolve().parent.parent
if str(PROJECT_DIR) not in sys.path:
    sys.path.insert(0, str(PROJECT_DIR))

WORKSPACE_DIR = PROJECT_DIR / ".atlas_cli"
UPLOAD_DIR = WORKSPACE_DIR / "uploads"
PRODUCT_PROJECTS_PATH = WORKSPACE_DIR / "gui_projects.json"
REPORTS_DIR = PROJECT_DIR / "reports"
DEPLOYMENTS_DIR = PROJECT_DIR / "deployments"
ALLOWED_UPLOAD_SUFFIXES = {".csv", ".json", ".parquet"}

app = FastAPI(
    title="Gradient Boosting Classifier Inference API",
    description="Production ML microservice generated by Atlas CLI.",
    version="1.0.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Load artifacts
MODEL_DIR = Path(__file__).parent / "model"
MODEL_PATH = MODEL_DIR / "model.joblib"
PIPELINE_PATH = MODEL_DIR / "pipeline.joblib"

estimator: Any = None
pipeline: Any = None

@app.on_event("startup")
def load_artifacts():
    global estimator, pipeline
    if not MODEL_PATH.exists():
        raise RuntimeError(f"Model artifact not found: {MODEL_PATH}")
    estimator = joblib.load(MODEL_PATH)
    logger.info(f"Loaded model: {MODEL_PATH}")

    if PIPELINE_PATH.exists():
        pipeline = joblib.load(PIPELINE_PATH)
        logger.info(f"Loaded preprocessing pipeline: {PIPELINE_PATH}")


def _record_to_features(inp: PredictionInput) -> list:
    return [inp.age, inp.sex, inp.cp, inp.trestbps, inp.chol, inp.fbs, inp.restecg, inp.thalach, inp.exang, inp.oldpeak, inp.slope, inp.ca, inp.thal]


def _transform_and_predict(features_matrix: np.ndarray) -> tuple[np.ndarray, np.ndarray | None]:
    if pipeline is not None:
        features_matrix = pipeline.transform(features_matrix)

    preds = estimator.predict(features_matrix)
    probas = None
    if hasattr(estimator, "predict_proba"):
        try:
            probas = estimator.predict_proba(features_matrix)
        except Exception:
            pass
    return preds, probas


@app.get("/health", tags=["Health"])
def health():
    return {"status": "healthy", "model_loaded": estimator is not None}


def _safe_run_id(run_id: str) -> str:
    if not run_id or Path(run_id).name != run_id or run_id in {".", ".."}:
        raise HTTPException(status_code=400, detail="Invalid run ID.")
    return run_id


def _find_latest_run_id() -> str | None:
    runs_dir = WORKSPACE_DIR / "runs"
    if not runs_dir.exists():
        return None
    runs = [item for item in runs_dir.iterdir() if item.is_dir()]
    return max(runs, key=lambda item: item.stat().st_mtime).name if runs else None


def _exec_atlas_cmd(command_line: list[str]) -> tuple[int, str]:
    import os
    env = dict(os.environ)
    env["PYTHONIOENCODING"] = "utf-8"
    res = subprocess.run(
        command_line,
        cwd=str(PROJECT_DIR),
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        encoding="utf-8",
        errors="replace",
        env=env,
    )
    return res.returncode, res.stdout


async def _run_atlas_command(command: str, args: list[str]) -> dict[str, Any]:
    """Run the existing Atlas CLI with JSON-safe captured output for the GUI."""
    command_line = [sys.executable, "-m", "atlas_cli.cli.main", command, *args]
    returncode, output = await asyncio.to_thread(_exec_atlas_cmd, command_line)
    if returncode != 0:
        raise HTTPException(
            status_code=400,
            detail={"message": f"atlas {command} failed", "output": output},
        )
    return {"command": f"atlas {command}", "output": output, "run_id": _find_latest_run_id()}


@app.post("/workspace/init", tags=["Atlas workspace"])
async def initialize_workspace():
    return await _run_atlas_command("init", [])


@app.post("/datasets/upload", tags=["Atlas workspace"])
async def upload_dataset(file: UploadFile = File(...)):
    suffix = Path(file.filename or "").suffix.lower()
    if suffix not in ALLOWED_UPLOAD_SUFFIXES:
        raise HTTPException(status_code=400, detail="Upload a CSV, JSON, or Parquet dataset.")
    UPLOAD_DIR.mkdir(parents=True, exist_ok=True)
    safe_name = Path(file.filename or "dataset").name
    destination = UPLOAD_DIR / safe_name
    with destination.open("wb") as target:
        shutil.copyfileobj(file.file, target)
    return {"file_name": safe_name, "path": str(destination.relative_to(PROJECT_DIR)).replace("\\", "/")}


@app.get("/runs", tags=["Atlas workspace"])
async def list_runs():
    runs_dir = WORKSPACE_DIR / "runs"
    if not runs_dir.exists():
        return []
    results = []
    for directory in sorted((item for item in runs_dir.iterdir() if item.is_dir()), key=lambda item: item.stat().st_mtime, reverse=True):
        artifacts = [item.name for item in directory.iterdir() if item.is_file()]
        summary = _read_json(directory / "dataset_summary.json")
        plan = _read_json(directory / "execution_plan.json")
        results.append({
            "id": directory.name,
            "updated_at": directory.stat().st_mtime,
            "dataset": summary.get("file_name"),
            "goal": plan.get("goal") or plan.get("reasoning"),
            "artifacts": artifacts,
        })
    return results


def _read_json(path: Path) -> dict[str, Any]:
    try:
        return json.loads(path.read_text(encoding="utf-8")) if path.exists() else {}
    except (OSError, json.JSONDecodeError):
        return {}


@app.get("/runs/{run_id}", tags=["Atlas workspace"])
async def get_run(run_id: str):
    directory = WORKSPACE_DIR / "runs" / _safe_run_id(run_id)
    if not directory.exists():
        raise HTTPException(status_code=404, detail="Run not found.")
    payload = {"id": run_id, "artifacts": {}}
    for artifact in directory.iterdir():
        if artifact.suffix == ".json":
            payload["artifacts"][artifact.name] = _read_json(artifact)
        elif artifact.is_file():
            payload["artifacts"][artifact.name] = {"download": f"/runs/{run_id}/files/{artifact.name}"}
    return payload


@app.get("/runs/{run_id}/files/{filename}", tags=["Atlas workspace"])
async def download_artifact(run_id: str, filename: str):
    directory = WORKSPACE_DIR / "runs" / _safe_run_id(run_id)
    path = directory / Path(filename).name
    if not path.is_file():
        raise HTTPException(status_code=404, detail="Artifact not found.")
    return FileResponse(path, filename=path.name)


@app.post("/atlas/analyze", tags=["Atlas commands"])
async def atlas_analyze(body: dict[str, Any]):
    args = [str(body.get("file_path", ""))]
    if body.get("target"):
        args += ["--target", str(body["target"])]
    if body.get("run_id"):
        args += ["--run-id", str(body["run_id"])]
    return await _run_atlas_command("analyze", args)


@app.post("/atlas/plan", tags=["Atlas commands"])
async def atlas_plan(body: dict[str, Any]):
    args = [str(body.get("file_path", "")), "--goal", str(body.get("goal", ""))]
    for field, option in (("target", "--target"), ("run_id", "--run-id"), ("model", "--model")):
        if body.get(field):
            args += [option, str(body[field])]
    return await _run_atlas_command("plan", args)


@app.post("/atlas/clean", tags=["Atlas commands"])
async def atlas_clean(body: dict[str, Any]):
    args = [str(body.get("file_path", ""))]
    for field, option in (("target", "--target"), ("run_id", "--run-id")):
        if body.get(field):
            args += [option, str(body[field])]
    return await _run_atlas_command("clean", args)


@app.post("/atlas/{command}", tags=["Atlas commands"])
async def atlas_command(command: str, body: dict[str, Any]):
    allowed = {"clean", "experiment", "compare", "review", "explain", "report", "deploy", "replay", "ask"}
    if command not in allowed:
        raise HTTPException(status_code=404, detail="Unsupported Atlas command.")
    args: list[str] = []
    if command == "ask":
        args.append(str(body.get("query", "")))
    elif command == "replay":
        args.append(str(body.get("run_id", "")))
    else:
        option_map = {"run_id": "--run-id", "parallel": "--parallel", "seed": "--seed", "model": "--model", "experiment_id": "--exp-id", "output_dir": "--out"}
        for field, option in option_map.items():
            if body.get(field) not in (None, ""):
                args += [option, str(body[field])]
    return await _run_atlas_command(command, args)


# Product API ---------------------------------------------------------------
# These endpoints intentionally expose projects and outcomes rather than CLI
# commands. They use the same Atlas workflow internally, while the GUI never
# needs to show run IDs, artifacts, or terminal output to end users.
def _load_projects() -> list[dict[str, Any]]:
    try:
        return json.loads(PRODUCT_PROJECTS_PATH.read_text(encoding="utf-8")) if PRODUCT_PROJECTS_PATH.exists() else []
    except (OSError, json.JSONDecodeError):
        return []


def _save_projects(projects: list[dict[str, Any]]) -> None:
    WORKSPACE_DIR.mkdir(parents=True, exist_ok=True)
    PRODUCT_PROJECTS_PATH.write_text(json.dumps(projects, indent=2), encoding="utf-8")


def _get_project(project_id: str) -> dict[str, Any]:
    for project in _load_projects():
        if project["id"] == project_id:
            return project
    raise HTTPException(status_code=404, detail="Project not found.")


def _project_run_dir(project: dict[str, Any]) -> Path:
    return WORKSPACE_DIR / "runs" / project["run_id"]


def _product_snapshot(project: dict[str, Any]) -> dict[str, Any]:
    run_dir = _project_run_dir(project)
    dataset = _read_json(run_dir / "dataset_summary.json")
    quality = _read_json(run_dir / "quality_report.json")
    risks = _read_json(run_dir / "risk_assessment.json")
    plan = _read_json(run_dir / "execution_plan.json")
    experiments = _read_json(run_dir / "experiment_results.json")
    comparison = _read_json(run_dir / "comparison_results.json")
    explanation = _read_json(run_dir / "explainability_results.json")
    critique = _read_json(run_dir / "critique_report.json")
    snapshot = _read_json(run_dir / "reproducibility_snapshot.json")
    report_dir = REPORTS_DIR / project["id"]
    deployment_dir = DEPLOYMENTS_DIR / project["id"]

    completed = {
        "data_health": bool(dataset),
        "model_plan": bool(plan),
        "training": bool(experiments),
        "explainability": bool(explanation),
        "report": (report_dir / "REPORT.html").exists(),
        "deployment": (deployment_dir / "main.py").exists(),
    }
    stage = "setup"
    for candidate, flag in (("data_health", completed["data_health"]), ("model_plan", completed["model_plan"]), ("training", completed["training"]), ("explainability", completed["explainability"])):
        if flag:
            stage = candidate

    # Deployment file listing
    deployment_files = []
    if deployment_dir.exists():
        for f in sorted(deployment_dir.iterdir()):
            if f.is_file():
                deployment_files.append({"name": f.name, "size": f.stat().st_size, "url": f"/product/projects/{project['id']}/deployment/{f.name}"})

    # Profile stats from dataset summary
    profile_stats = dataset.get("profile", {}).get("columns", dataset.get("column_stats", []))

    # SHAP plot availability
    shap_summary_exists = (run_dir / "shap_summary.png").exists()
    shap_importance_exists = (run_dir / "shap_importance.png").exists()

    return {
        "id": project["id"],
        "name": project["name"],
        "created_at": project["created_at"],
        "updated_at": project.get("updated_at", project["created_at"]),
        "stage": stage,
        "completed": completed,
        "dataset": {
            "name": project["dataset_name"],
            "target": project.get("target") or plan.get("target_column"),
            "goal": project.get("goal", ""),
            "rows": dataset.get("num_rows"),
            "columns": dataset.get("num_cols"),
        },
        "data_health": {
            "duplicate_rows": quality.get("duplicate_rows"),
            "duplicate_pct": quality.get("duplicate_pct"),
            "severity": risks.get("overall_severity"),
            "risks": risks.get("risks", []),
            "columns": dataset.get("schema", {}).get("columns", []),
            "profile_stats": profile_stats if isinstance(profile_stats, list) else [],
            "target_distribution": quality.get("target_distribution") or dataset.get("target_distribution"),
        },
        "plan": {
            "task_type": plan.get("task_type"),
            "target_column": plan.get("target_column"),
            "reasoning": plan.get("reasoning"),
            "preprocessing": plan.get("preprocessing", {}),
            "feature_engineering": plan.get("feature_engineering", {}),
            "evaluation": plan.get("evaluation", {}),
            "models": plan.get("model_candidates", []),
        },
        "results": {
            "primary_metric": experiments.get("primary_metric") or comparison.get("primary_metric"),
            "experiments": experiments.get("experiments", []),
            "winner": comparison.get("winner"),
            "rankings": comparison.get("rankings", []),
        },
        "explanation": {
            "model_name": explanation.get("model_name"),
            "metric": explanation.get("primary_metric"),
            "metric_value": explanation.get("primary_metric_value"),
            "features": explanation.get("global_importances", []),
            "narrative": explanation.get("feature_impact_narrative"),
            "why_chosen": explanation.get("why_chosen_narrative"),
            "has_shap_summary": shap_summary_exists,
            "has_shap_importance": shap_importance_exists,
        },
        "critique": {
            "diagnosis": (
                critique.get("opt_rationale")
                or (critique.get("refinement_plan", {}).get("critique_summary") if isinstance(critique.get("refinement_plan"), dict) else None)
                or (critique.get("diagnosis", {}).get("overall_health") if isinstance(critique.get("diagnosis"), dict) else critique.get("diagnosis"))
                or critique.get("critique")
                or "Model review complete."
            ),
            "actions": critique.get("actions", []),
            "refined_model": critique.get("refined_model_name") or critique.get("refined_model"),
            "before_metrics": critique.get("before_metrics", {}),
            "after_metrics": critique.get("after_metrics", {}),
            "improvement": critique.get("improvement"),
        } if critique else None,
        "delivery": {
            "report_url": f"/product/projects/{project['id']}/report" if (report_dir / "REPORT.html").exists() else None,
            "deployment_ready": completed["deployment"],
            "deployment_files": deployment_files,
        },
        "reproducibility": {
            "dataset_sha256": snapshot.get("dataset_sha256"),
            "git_commit": snapshot.get("git_commit"),
            "python_version": snapshot.get("python_version"),
            "os_info": snapshot.get("os_info"),
            "random_seed": snapshot.get("random_seed"),
            "dependencies": snapshot.get("dependencies", {}),
            "created_at": snapshot.get("created_at"),
        } if snapshot else None,
    }


def _project_error(action: str) -> HTTPException:
    messages = {
        "data_health": "We couldn't finish reviewing this dataset. Check the file format and try again.",
        "model_plan": "Atlas couldn't create a modeling plan yet. Check your AI connection in Settings and try again.",
        "training": "The models couldn't be trained. Review your data setup, then try again.",
        "improve": "Atlas couldn't improve this model right now. Try again after training completes.",
        "explainability": "An explanation could not be generated for this model.",
        "report": "Your report could not be created right now.",
        "deployment": "Your deployment package could not be prepared right now.",
        "ask": "Atlas couldn't answer that question right now. Please try again.",
    }
    return HTTPException(status_code=400, detail=messages.get(action, "That action could not be completed."))


@app.post("/product/projects", tags=["Atlas product"])
async def create_product_project(
    file: UploadFile = File(...),
    name: str = Form("Untitled project"),
    goal: str = Form(""),
    target: str = Form(""),
):
    suffix = Path(file.filename or "").suffix.lower()
    if suffix not in ALLOWED_UPLOAD_SUFFIXES:
        raise HTTPException(status_code=400, detail="Choose a CSV, JSON, or Parquet data file.")
    project_id = uuid.uuid4().hex[:10]
    project_upload_dir = UPLOAD_DIR / project_id
    project_upload_dir.mkdir(parents=True, exist_ok=True)
    safe_name = Path(file.filename or "dataset").name
    destination = project_upload_dir / safe_name
    with destination.open("wb") as target_file:
        shutil.copyfileobj(file.file, target_file)
    timestamp = datetime.now(timezone.utc).isoformat()
    project = {
        "id": project_id,
        "name": name.strip() or "Untitled project",
        "dataset_name": safe_name,
        "dataset_path": str(destination.relative_to(PROJECT_DIR)).replace("\\", "/"),
        "goal": goal.strip(),
        "target": target.strip(),
        "run_id": project_id,
        "created_at": timestamp,
        "updated_at": timestamp,
    }
    projects = _load_projects()
    projects.append(project)
    _save_projects(projects)
    try:
        from atlas_cli.db.session import create_db_and_tables
        create_db_and_tables()
    except Exception:
        logger.warning("Could not initialize optional Atlas database for product project.", exc_info=True)
    return _product_snapshot(project)


@app.get("/product/projects", tags=["Atlas product"])
async def list_product_projects():
    projects = [_product_snapshot(project) for project in _load_projects()]
    return sorted(projects, key=lambda project: project["updated_at"], reverse=True)


@app.get("/product/projects/{project_id}", tags=["Atlas product"])
async def get_product_project(project_id: str):
    return _product_snapshot(_get_project(project_id))


@app.post("/product/projects/{project_id}/{action}", tags=["Atlas product"])
async def run_product_action(project_id: str, action: str, body: dict[str, Any] | None = None):
    project = _get_project(project_id)
    body = body or {}
    path = project["dataset_path"]
    run_id = project["run_id"]
    try:
        if action == "data_health":
            args = [path, "--run-id", run_id]
            if project.get("target"):
                args += ["--target", project["target"]]
            await _run_atlas_command("analyze", args)
        elif action == "model_plan":
            if not project.get("goal"):
                raise HTTPException(status_code=400, detail="Tell Atlas what you want to predict before creating a plan.")
            args = [path, "--goal", project["goal"], "--run-id", run_id]
            if project.get("target"):
                args += ["--target", project["target"]]
            if body.get("model"):
                args += ["--model", str(body["model"])]
            await _run_atlas_command("plan", args)
        elif action == "training":
            await _run_atlas_command("experiment", ["--run-id", run_id, "--parallel", str(body.get("parallel", 4))])
            await _run_atlas_command("compare", ["--run-id", run_id])
        elif action == "improve":
            await _run_atlas_command("review", ["--run-id", run_id])
        elif action == "explainability":
            await _run_atlas_command("explain", ["--run-id", run_id])
        elif action == "report":
            await _run_atlas_command("report", ["--run-id", run_id, "--out", str(REPORTS_DIR / project_id)])
        elif action == "deployment":
            await _run_atlas_command("deploy", ["--run-id", run_id, "--out", str(DEPLOYMENTS_DIR / project_id)])
        elif action == "replay":
            await _run_atlas_command("replay", [run_id])
        elif action == "ask":
            question = str(body.get("question", "")).strip().strip('"').strip("'").strip()
            if not question:
                raise HTTPException(status_code=400, detail="Write a question for Atlas first.")
            from atlas_cli.agents.assistant.reasoning import answer_query
            answer = await asyncio.to_thread(answer_query, question, run_id)
            return {"answer": answer.strip()}
        else:
            raise HTTPException(status_code=404, detail="That action is not available.")
    except HTTPException as exc:
        if exc.status_code == 404 or (isinstance(exc.detail, str) and "before" in exc.detail):
            raise
        if isinstance(exc.detail, dict) and "output" in exc.detail:
            raise HTTPException(status_code=400, detail=exc.detail.get("output", str(exc.detail)))
        if isinstance(exc.detail, str) and exc.detail:
            raise
        raise _project_error(action) from exc
    project["updated_at"] = datetime.now(timezone.utc).isoformat()
    projects = _load_projects()
    for index, current in enumerate(projects):
        if current["id"] == project_id:
            projects[index] = project
            break
    _save_projects(projects)
    messages = {
        "data_health": "Your data health check is ready.",
        "model_plan": "Your modeling plan is ready.",
        "training": "Training is complete. Atlas selected a recommended model.",
        "improve": "Atlas has reviewed and refined the model.",
        "explainability": "Your model explanation is ready.",
        "report": "Your shareable report is ready.",
        "deployment": "Your deployment package is ready.",
        "replay": "Reproducibility replay completed successfully.",
    }
    return {"message": messages.get(action, "Action completed."), "project": _product_snapshot(project)}


@app.get("/product/projects/{project_id}/report", tags=["Atlas product"])
async def product_report(project_id: str):
    _get_project(project_id)
    report = REPORTS_DIR / project_id / "REPORT.html"
    if not report.exists():
        raise HTTPException(status_code=404, detail="A report has not been created yet.")
    return FileResponse(report, media_type="text/html", filename="Atlas-report.html")


@app.get("/product/projects/{project_id}/deployment/{filename}", tags=["Atlas product"])
async def product_deployment_file(project_id: str, filename: str):
    _get_project(project_id)
    safe_name = Path(filename).name
    filepath = DEPLOYMENTS_DIR / project_id / safe_name
    if not filepath.is_file():
        raise HTTPException(status_code=404, detail="Deployment file not found.")
    return FileResponse(filepath, filename=safe_name)


@app.get("/product/projects/{project_id}/shap/{plot_name}", tags=["Atlas product"])
async def product_shap_plot(project_id: str, plot_name: str):
    project = _get_project(project_id)
    run_dir = _project_run_dir(project)
    safe_name = Path(plot_name).name
    filepath = run_dir / safe_name
    if not filepath.is_file() or not safe_name.endswith(".png"):
        raise HTTPException(status_code=404, detail="SHAP plot not found.")
    return FileResponse(filepath, media_type="image/png", filename=safe_name)


@app.get("/info", response_model=ServiceInfo, tags=["Metadata"])
def info():
    return ServiceInfo(
        model_name="Gradient Boosting Classifier",
        library="sklearn.ensemble.GradientBoostingClassifier",
        task_type="binary_classification",
        status="healthy" if estimator is not None else "degraded",
    )


@app.post("/predict", response_model=PredictionOutput, tags=["Inference"])
def predict(inp: PredictionInput):
    if estimator is None:
        raise HTTPException(status_code=503, detail="Model is not loaded.")

    try:
        raw_feats = _record_to_features(inp)
        X = np.array([raw_feats], dtype=object if any(isinstance(v, str) for v in raw_feats) else float)

        # Build DataFrame if features are named
        if hasattr(inp, "model_dump"):
            df = pd.DataFrame([inp.model_dump()])
            preds, probas = _transform_and_predict(df if pipeline is not None else X)
        else:
            preds, probas = _transform_and_predict(X)

        pred_val = preds[0]
        if isinstance(pred_val, (np.generic, np.ndarray)):
            pred_val = pred_val.item()

        prob_list = None
        if probas is not None:
            prob_list = [float(p) for p in probas[0]]

        return PredictionOutput(
            prediction=pred_val,
            probabilities=prob_list,
            model_name="Gradient Boosting Classifier",
        )
    except Exception as exc:
        logger.error(f"Inference error: {exc}", exc_info=True)
        raise HTTPException(status_code=500, detail=str(exc))


@app.post("/predict_batch", response_model=PredictionBatchOutput, tags=["Inference"])
def predict_batch(batch: PredictionBatchInput):
    if estimator is None:
        raise HTTPException(status_code=503, detail="Model is not loaded.")

    try:
        records = [inp.model_dump() for inp in batch.instances]
        df = pd.DataFrame(records)

        preds, probas = _transform_and_predict(df)

        outputs = []
        for i, pred in enumerate(preds):
            pval = pred.item() if isinstance(pred, (np.generic, np.ndarray)) else pred
            plist = [float(p) for p in probas[i]] if probas is not None else None
            outputs.append(
                PredictionOutput(
                    prediction=pval,
                    probabilities=plist,
                    model_name="Gradient Boosting Classifier",
                )
            )

        return PredictionBatchOutput(predictions=outputs, count=len(outputs))
    except Exception as exc:
        logger.error(f"Batch inference error: {exc}", exc_info=True)
        raise HTTPException(status_code=500, detail=str(exc))


if __name__ == "__main__":
    import uvicorn
    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=True)
