"""
Production FastAPI Microservice for Gradient Boosting Classifier.
Auto-generated by Atlas CLI Deployment Generator.
"""
from __future__ import annotations

import logging
from pathlib import Path
from typing import Any

import joblib
import numpy as np
import pandas as pd
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware

from schemas import (
    PredictionBatchInput,
    PredictionBatchOutput,
    PredictionInput,
    PredictionOutput,
    ServiceInfo,
)

logger = logging.getLogger("model_service")
logging.basicConfig(level=logging.INFO)

app = FastAPI(
    title="Gradient Boosting Classifier Inference API",
    description="Production ML microservice generated by Atlas CLI.",
    version="1.0.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Load artifacts
MODEL_DIR = Path(__file__).parent / "model"
MODEL_PATH = MODEL_DIR / "model.joblib"
PIPELINE_PATH = MODEL_DIR / "pipeline.joblib"

estimator: Any = None
pipeline: Any = None

@app.on_event("startup")
def load_artifacts():
    global estimator, pipeline
    if not MODEL_PATH.exists():
        raise RuntimeError(f"Model artifact not found: {MODEL_PATH}")
    estimator = joblib.load(MODEL_PATH)
    logger.info(f"Loaded model: {MODEL_PATH}")

    if PIPELINE_PATH.exists():
        pipeline = joblib.load(PIPELINE_PATH)
        logger.info(f"Loaded preprocessing pipeline: {PIPELINE_PATH}")


def _record_to_features(inp: PredictionInput) -> list:
    return [inp.age, inp.sex, inp.cp, inp.trestbps, inp.chol, inp.fbs, inp.restecg, inp.thalach, inp.exang, inp.oldpeak, inp.slope, inp.ca, inp.thal]


def _transform_and_predict(features_matrix: np.ndarray) -> tuple[np.ndarray, np.ndarray | None]:
    if pipeline is not None:
        features_matrix = pipeline.transform(features_matrix)

    preds = estimator.predict(features_matrix)
    probas = None
    if hasattr(estimator, "predict_proba"):
        try:
            probas = estimator.predict_proba(features_matrix)
        except Exception:
            pass
    return preds, probas


@app.get("/health", tags=["Health"])
def health():
    return {"status": "healthy", "model_loaded": estimator is not None}


@app.get("/info", response_model=ServiceInfo, tags=["Metadata"])
def info():
    return ServiceInfo(
        model_name="Gradient Boosting Classifier",
        library="sklearn.ensemble.GradientBoostingClassifier",
        task_type="binary_classification",
        status="healthy" if estimator is not None else "degraded",
    )


@app.post("/predict", response_model=PredictionOutput, tags=["Inference"])
def predict(inp: PredictionInput):
    if estimator is None:
        raise HTTPException(status_code=503, detail="Model is not loaded.")

    try:
        raw_feats = _record_to_features(inp)
        X = np.array([raw_feats], dtype=object if any(isinstance(v, str) for v in raw_feats) else float)

        # Build DataFrame if features are named
        if hasattr(inp, "model_dump"):
            df = pd.DataFrame([inp.model_dump()])
            preds, probas = _transform_and_predict(df if pipeline is not None else X)
        else:
            preds, probas = _transform_and_predict(X)

        pred_val = preds[0]
        if isinstance(pred_val, (np.generic, np.ndarray)):
            pred_val = pred_val.item()

        prob_list = None
        if probas is not None:
            prob_list = [float(p) for p in probas[0]]

        return PredictionOutput(
            prediction=pred_val,
            probabilities=prob_list,
            model_name="Gradient Boosting Classifier",
        )
    except Exception as exc:
        logger.error(f"Inference error: {exc}", exc_info=True)
        raise HTTPException(status_code=500, detail=str(exc))


@app.post("/predict_batch", response_model=PredictionBatchOutput, tags=["Inference"])
def predict_batch(batch: PredictionBatchInput):
    if estimator is None:
        raise HTTPException(status_code=503, detail="Model is not loaded.")

    try:
        records = [inp.model_dump() for inp in batch.instances]
        df = pd.DataFrame(records)

        preds, probas = _transform_and_predict(df)

        outputs = []
        for i, pred in enumerate(preds):
            pval = pred.item() if isinstance(pred, (np.generic, np.ndarray)) else pred
            plist = [float(p) for p in probas[i]] if probas is not None else None
            outputs.append(
                PredictionOutput(
                    prediction=pval,
                    probabilities=plist,
                    model_name="Gradient Boosting Classifier",
                )
            )

        return PredictionBatchOutput(predictions=outputs, count=len(outputs))
    except Exception as exc:
        logger.error(f"Batch inference error: {exc}", exc_info=True)
        raise HTTPException(status_code=500, detail=str(exc))


if __name__ == "__main__":
    import uvicorn
    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=True)
