"""
Pydantic Request & Response Schemas.
Auto-generated by Atlas CLI Deployment Generator.
"""
from __future__ import annotations

from typing import Any, Optional
from pydantic import BaseModel, Field


class PredictionInput(BaseModel):
    """Input payload for a single prediction request."""
    age: int = Field(..., description="Feature 'age'")
    sex: int = Field(..., description="Feature 'sex'")
    cp: int = Field(..., description="Feature 'cp'")
    trestbps: int = Field(..., description="Feature 'trestbps'")
    chol: int = Field(..., description="Feature 'chol'")
    fbs: int = Field(..., description="Feature 'fbs'")
    restecg: int = Field(..., description="Feature 'restecg'")
    thalach: int = Field(..., description="Feature 'thalach'")
    exang: int = Field(..., description="Feature 'exang'")
    oldpeak: float = Field(..., description="Feature 'oldpeak'")
    slope: int = Field(..., description="Feature 'slope'")
    ca: int = Field(..., description="Feature 'ca'")
    thal: int = Field(..., description="Feature 'thal'")

    model_config = {
        "json_schema_extra": {
            "examples": [
{
        "age": 52,
        "sex": 1,
        "cp": 0,
        "trestbps": 125,
        "chol": 212,
        "fbs": 0,
        "restecg": 1,
        "thalach": 168,
        "exang": 0,
        "oldpeak": 1.0,
        "slope": 2,
        "ca": 2,
        "thal": 3
}
            ]
        }
    }


class PredictionBatchInput(BaseModel):
    """Batch input payload for multiple prediction requests."""
    instances: list[PredictionInput] = Field(..., description="List of feature records")


class PredictionOutput(BaseModel):
    """Output prediction response."""
    prediction: Any = Field(..., description="Predicted label or value")
    probabilities: Optional[list[float]] = None
    model_name: str = Field(..., description="Serving model name")


class PredictionBatchOutput(BaseModel):
    """Batch prediction response."""
    predictions: list[PredictionOutput] = Field(..., description="List of prediction responses")
    count: int = Field(..., description="Number of instances processed")


class ServiceInfo(BaseModel):
    """Service metadata information."""
    service_name: str = "Atlas CLI Model Microservice"
    version: str = "1.0.0"
    model_name: str
    library: str
    task_type: str
    status: str = "healthy"
