"""
Standalone Production Inference Package Generator — Phase 6 Module.

Generates a self-contained CLI Python script `predict.py` in the run directory (.atlas_cli/runs/<run_id>/predict.py)
that loads `pipeline.joblib` and the winning model `.joblib` to execute predictions on new datasets.
"""
from __future__ import annotations

import logging
from pathlib import Path

from atlas_cli.agents.comparator.scorer import RankedExperiment
from atlas_cli.core.config import settings

logger = logging.getLogger("atlas_cli")


def generate_inference_script(run_id: str, winner: RankedExperiment) -> Path:
    """
    Generate a standalone predict.py script for production inference.

    Args:
        run_id: Run identifier.
        winner: Winning RankedExperiment object.

    Returns:
        Path to the generated predict.py script.
    """
    run_dir = settings.workspace_dir / "runs" / run_id
    safe_name = winner.model_name.lower().replace(" ", "_").replace("/", "_")
    model_filename = f"{safe_name}.joblib"

    script_content = f'''"""
Standalone Production Inference Script — Generated by Atlas CLI.
Run ID: {run_id}
Winning Model: {winner.model_name} ({winner.library})

Usage:
    python predict.py --input input_data.csv --output predictions.csv
"""
import argparse
import sys
from pathlib import Path
import pandas as pd
import joblib

RUN_DIR = Path(__file__).parent.resolve()
WORKSPACE_DIR = RUN_DIR.parent.parent.parent.resolve()
if str(WORKSPACE_DIR) not in sys.path:
    sys.path.insert(0, str(WORKSPACE_DIR))

# Ensure custom transformers are registered for joblib unpickling
try:
    import atlas_cli
except ImportError:
    pass

PIPELINE_PATH = RUN_DIR / "pipeline.joblib"
MODEL_PATH = RUN_DIR / "models" / "{model_filename}"


def predict_file(input_path: str, output_path: str | None = None) -> pd.DataFrame:
    """Load input CSV, apply pipeline transformation, and run inference using winning model."""
    if not PIPELINE_PATH.exists():
        raise FileNotFoundError(f"Feature engineering pipeline artifact missing: {{PIPELINE_PATH}}")
    if not MODEL_PATH.exists():
        raise FileNotFoundError(f"Model artifact missing: {{MODEL_PATH}}")

    print(f"Loading pipeline: {{PIPELINE_PATH.name}}...")
    pipeline = joblib.load(PIPELINE_PATH)

    print(f"Loading winning model ({winner.model_name}): {{MODEL_PATH.name}}...")
    model = joblib.load(MODEL_PATH)

    print(f"Reading input data: {{input_path}}...")
    df_raw = pd.read_csv(input_path)

    # Transform features using fitted pipeline
    X_transformed = pipeline.transform(df_raw)

    print("Running model inference...")
    predictions = model.predict(X_transformed)
    df_out = df_raw.copy()
    df_out["predicted_outcome"] = predictions

    if hasattr(model, "predict_proba"):
        try:
            probas = model.predict_proba(X_transformed)
            if probas.shape[1] == 2:
                df_out["prediction_confidence"] = probas[:, 1]
            else:
                for i in range(probas.shape[1]):
                    df_out[f"prob_class_{{i}}"] = probas[:, i]
        except Exception:
            pass

    if output_path:
        df_out.to_csv(output_path, index=False)
        print(f"SUCCESS: Predictions saved to: {{output_path}}")

    return df_out


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Atlas CLI Standalone Production Inference")
    parser.add_argument("--input", "-i", required=True, help="Path to input CSV dataset")
    parser.add_argument("--output", "-o", default=None, help="Path to output CSV predictions file")
    args = parser.parse_args()

    predict_file(args.input, args.output)
'''

    predict_path = run_dir / "predict.py"
    predict_path.write_text(script_content, encoding="utf-8")
    logger.info(f"Generated standalone inference package: {predict_path}")
    return predict_path
