"""
Reviewer Schemas — Phase 7.
Pydantic v2 schemas for model diagnostics, LLM reflection critique,
refinement plans, and complete critique reports.
"""
from __future__ import annotations

from typing import Any, Literal, Optional
from pydantic import BaseModel, Field

Severity = Literal["low", "medium", "high", "critical"]
IssueCategory = Literal[
    "overfitting",
    "underfitting",
    "class_imbalance",
    "high_latency",
    "high_complexity",
    "none",
]


class DiagnosticIssue(BaseModel):
    """Specific model issue detected by rule-based diagnostics."""

    category: IssueCategory = Field(..., description="Issue category (e.g. overfitting).")
    severity: Severity = Field(..., description="Severity level.")
    description: str = Field(..., description="Human-readable description of the issue.")
    metric_gap: Optional[float] = Field(None, description="Difference between train and val metrics, if applicable.")
    recommendation: str = Field(..., description="Actionable recommendation to fix the issue.")


class DiagnosisResult(BaseModel):
    """Rule-based diagnostic assessment for a model candidate."""

    model_name: str
    has_issues: bool = False
    issues: list[DiagnosticIssue] = Field(default_factory=list)
    overall_health: Literal["healthy", "warning", "critical"] = "healthy"
    suggested_params: dict[str, Any] = Field(default_factory=dict)


class RefinementPlan(BaseModel):
    """Structured refinement plan generated by LLM critique / heuristics."""

    target_model_name: str = Field(..., description="Name of the model being refined.")
    target_library: str = Field(..., description="Library identifier of the model.")
    critique_summary: str = Field(..., description="Natural language critique of model performance & gaps.")
    root_cause_analysis: str = Field(..., description="Explanation of why the model overfitted/underperformed.")
    proposed_adjustments: str = Field(..., description="Summary of hyperparameter and structural changes.")
    refined_hyperparams: dict[str, Any] = Field(
        default_factory=dict,
        description="Exact parameter dictionary to instantiate the refined candidate.",
    )


class RefinedExperimentComparison(BaseModel):
    """Side-by-side metric comparison between initial and refined model runs."""

    model_name: str
    primary_metric_name: str
    initial_train_metric: float = 0.0
    initial_val_metric: float = 0.0
    initial_test_metric: float = 0.0
    refined_train_metric: float = 0.0
    refined_val_metric: float = 0.0
    refined_test_metric: float = 0.0
    gap_reduced: float = 0.0
    test_improved: bool = False
    verdict: str = ""


class CritiqueReport(BaseModel):
    """Complete summary report of the AI Reviewer & Auto-Critique Loop."""

    run_id: str
    task_type: str
    primary_metric: str
    initial_winner_name: str
    diagnosis: DiagnosisResult
    refinement_plan: RefinementPlan
    comparison: RefinedExperimentComparison
    refinement_successful: bool = False
    opt_rationale: str = ""
